name: lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm ci --ignore-scripts
      - run: npm run lint:js
      - run: npm run lint:css
      - run: npm run lint:prettier
